CREATE SEQUENCE IF NOT EXISTS SEQ_ID_PERSON
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 99999999;

CREATE TABLE IF NOT EXISTS PERSON (
    ID integer NOT NULL DEFAULT NEXTVAL('SEQ_ID_PERSON'),
    NAME VARCHAR(200) NOT NULL,
    CONSTRAINT PATIENT_PKEY PRIMARY KEY (ID)
);

INSERT INTO PERSON (name) VALUES ('João');
INSERT INTO PERSON (name) VALUES ('Maira');
INSERT INTO PERSON (name) VALUES ('Ana');
INSERT INTO PERSON (name) VALUES ('Júlia');
INSERT INTO PERSON (name) VALUES ('Pedro');
INSERT INTO PERSON (name) VALUES ('Francisco');
INSERT INTO PERSON (name) VALUES ('Joaquim');
INSERT INTO PERSON (name) VALUES ('José');
INSERT INTO PERSON (name) VALUES ('Lídia');
INSERT INTO PERSON (name) VALUES ('Estela');
INSERT INTO PERSON (name) VALUES ('Gabriela');
INSERT INTO PERSON (name) VALUES ('Rosa');
INSERT INTO PERSON (name) VALUES ('Abraão');
INSERT INTO PERSON (name) VALUES ('Tiago');
INSERT INTO PERSON (name) VALUES ('Everton');
INSERT INTO PERSON (name) VALUES ('Mariana');
INSERT INTO PERSON (name) VALUES ('Jéssica');
INSERT INTO PERSON (name) VALUES ('Daniela');
INSERT INTO PERSON (name) VALUES ('Camila');
INSERT INTO PERSON (name) VALUES ('Carolina');
INSERT INTO PERSON (name) VALUES ('Fernando');
INSERT INTO PERSON (name) VALUES ('Jaqueline');
INSERT INTO PERSON (name) VALUES ('Lívia');
INSERT INTO PERSON (name) VALUES ('Janaina');
INSERT INTO PERSON (name) VALUES ('Laura');
INSERT INTO PERSON (name) VALUES ('Janine');
INSERT INTO PERSON (name) VALUES ('Marcos');
INSERT INTO PERSON (name) VALUES ('Paulo');